name: Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  AppimageBuild:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Dependencies
      run: |
        sudo add-apt-repository universe
        sudo apt install libfuse2t64
        sudo apt-get -y install libsdl2-dev
    - name: Appimage
      run: make appimage
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: Appimage
        path: build/CemuShake-x86_64.AppImage

  Release:
    runs-on: ubuntu-24.04
    needs: AppimageBuild

    steps:
    - uses: actions/checkout@v4

    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: Appimage

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Delete existing local tag if exists
      run: |
        git tag -d latest || true

    - name: Delete remote tag if exists
      run: |
        git push --delete origin latest || true

    - name: Delete old GitHub release if exists
      run: |
        gh release delete latest --yes || true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create new tag
      run: |
        git tag latest
        git push origin latest --force

    - name: Create or update GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        files: CemuShake-x86_64.AppImage
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
